version: '3.8'

services:
  lambda-rie:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lambda-rie-test
    ports:
      - '9000:8080'
    environment:
      - AWS_LAMBDA_FUNCTION_NAME=test-esm-function
      - AWS_LAMBDA_FUNCTION_VERSION=1
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=128
      - OTEL_DEBUG_ENABLED=true
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:8080/2015-03-31/functions/function/invocations',
          '--data',
          '{}',
        ]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 5s
